language: go
go:
  - 1.7
install:
  - go get -v github.com/Masterminds/glide
  - glide install
env:
  global:
    - TEST_TIMEOUT_SCALE=20 # Set higher timeouts for Travis
    - PACKAGE=github.com/$TRAVIS_REPO_SLUG
script:
 - make all
